---
- name: Install Plex
  become: yes
  apt:
      deb: "https://downloads.plex.tv/plex-media-server/{{plex_version}}/plexmediaserver_{{plex_version}}_amd64.deb"
      state: present
  notify: 'restart-plex'
  when: (ansible_distribution == "Ubuntu") and (plex_install)

- name: Start Plex
  systemd:
      name: plexmediaserver
      state: started
      enabled: yes

- meta: flush_handlers
